descriptor:
  name: Teleposer Control
  description: A program to automate the shifting of Teleposition Focus to Teleposer from Blood Magic.
  repositoryLink: https://github.com/Navatusein/GTNH-OC-Teleposer-Control
  fieldGroups:
    - key: logger
      name: Logger
      defaultOpen: true
      fields:
        - key: name
          type: string
          default: Teleposer Control
          label: Name
          description: Name witch will be displayed in discord

        - key: timeZone
          type: integer
          default: 3
          label: Time Zone
          description: Your time zone

        - key: discordWebhookUrl
          type: url
          default: ""
          optional: true
          label: Discord Webhook Url
          description: Discord Webhook Url for notifications

    - key: teleposer
      label: Teleposer Controller
      fields:
        - key: teleposerSide
          type: side
          label: Teleposer Side
          description: Side of the transposer witch connected to teleposer
        
        - key: storageSide
          type: side
          label: Storage Side
          default: sides.up
          description: Side of the transposer witch connected storage chest

        - key: redstoneSide
          type: side
          label: Redstone Side
          default: sides.up
          description: Side of the Redstone I/O witch connected to teleposer

  configTemplate: |
    local sides = require("sides")

    local loggerLib = require("lib.logger-lib")
    local discordLoggerHandler = require("lib.logger-handler.discord-logger-handler-lib")
    local fileLoggerHandler = require("lib.logger-handler.file-logger-handler-lib")

    local teleposer = require("src.teleposer")

    local config = {
      enableAutoUpdate = true, -- Enable auto update on start

      logger = loggerLib:newFormConfig({
        name = "<field>name</field>",
        timeZone = <field>timeZone</field>, -- Your time zone
        handlers = {
          discordLoggerHandler:newFormConfig({
            logLevel = "warning",
            messageFormat = "{Time:%d.%m.%Y %H:%M:%S} [{LogLevel}]: {Message}",
            discordWebhookUrl = "<field>discordWebhookUrl</field>" -- Discord Webhook URL
          }),
          fileLoggerHandler:newFormConfig({
            logLevel = "info",
            messageFormat = "{Time:%d.%m.%Y %H:%M:%S} [{LogLevel}]: {Message}",
            filePath = "logs.log"
          })
        }
      }),

      teleposer = teleposer:newFormConfig({
        teleposerSide = <field>teleposerSide</field>, -- Side of the transposer witch connected to teleposer
        storageSide = <field>storageSide</field>, -- Side of the transposer witch connected storage chest
        redstoneSide = <field>redstoneSide</field> -- Side of the Redstone I/O witch connected to teleposer
      })
    }

    return config